# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Easyp < Formula
  desc "Easy modern protobuf tooling for all your needs."
  homepage "https://easyp.tech"
  version "0.12.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/easyp-tech/easyp/releases/download/v0.12.0/easyp-0.12.0-darwin-amd64.tar.gz"
      sha256 "cd16ed76e9399a0ad96dc96acaa52bbeb0c15108f045bf450c8037791b3bdc11"

      def install
        bin.install "easyp"
        output = Utils.popen_read("#{bin}/easyp completion bash")
        (bash_completion/"easyp").write output
        output = Utils.popen_read("#{bin}/easyp completion zsh")
        (zsh_completion/"_easyp").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/easyp-tech/easyp/releases/download/v0.12.0/easyp-0.12.0-darwin-arm64.tar.gz"
      sha256 "06426a1b186949548a1a471959042378b7d24ed889b45a6324b256e351de647c"

      def install
        bin.install "easyp"
        output = Utils.popen_read("#{bin}/easyp completion bash")
        (bash_completion/"easyp").write output
        output = Utils.popen_read("#{bin}/easyp completion zsh")
        (zsh_completion/"_easyp").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/easyp-tech/easyp/releases/download/v0.12.0/easyp-0.12.0-linux-amd64.tar.gz"
      sha256 "6355638b274e4b2541f41a3595514a3d9f52f958ccf93e36cbee488daab1ba64"
      def install
        bin.install "easyp"
        output = Utils.popen_read("#{bin}/easyp completion bash")
        (bash_completion/"easyp").write output
        output = Utils.popen_read("#{bin}/easyp completion zsh")
        (zsh_completion/"_easyp").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/easyp-tech/easyp/releases/download/v0.12.0/easyp-0.12.0-linux-armv6.tar.gz"
      sha256 "ed2e78cab6e41c3b56a03e25a4efda1f01eddc23f976d04c40df2e0955f6ddb6"
      def install
        bin.install "easyp"
        output = Utils.popen_read("#{bin}/easyp completion bash")
        (bash_completion/"easyp").write output
        output = Utils.popen_read("#{bin}/easyp completion zsh")
        (zsh_completion/"_easyp").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/easyp-tech/easyp/releases/download/v0.12.0/easyp-0.12.0-linux-arm64.tar.gz"
      sha256 "209b53c321f97a90b31b2a0c54a48f04f6c66ff9934449dfff17a7b4060d67a4"
      def install
        bin.install "easyp"
        output = Utils.popen_read("#{bin}/easyp completion bash")
        (bash_completion/"easyp").write output
        output = Utils.popen_read("#{bin}/easyp completion zsh")
        (zsh_completion/"_easyp").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/easyp --version"
  end
end
