# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Easyp < Formula
  desc "Easy modern protobuf tooling for all your needs."
  homepage "https://easyp.tech"
  version "0.7.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/easyp-tech/easyp/releases/download/v0.7.7/easyp-0.7.7-darwin-amd64.tar.gz"
      sha256 "5110ba295677620877bb1461edb23e19f80c6ea0bebdaea59f403f20a85c3c16"

      def install
        bin.install "easyp"
        output = Utils.popen_read("#{bin}/easyp completion bash")
        (bash_completion/"easyp").write output
        output = Utils.popen_read("#{bin}/easyp completion zsh")
        (zsh_completion/"_easyp").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/easyp-tech/easyp/releases/download/v0.7.7/easyp-0.7.7-darwin-arm64.tar.gz"
      sha256 "e21bb415811314cccf86255d2dfc84798d31da2d20fbcf12c5db7c95118bd474"

      def install
        bin.install "easyp"
        output = Utils.popen_read("#{bin}/easyp completion bash")
        (bash_completion/"easyp").write output
        output = Utils.popen_read("#{bin}/easyp completion zsh")
        (zsh_completion/"_easyp").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/easyp-tech/easyp/releases/download/v0.7.7/easyp-0.7.7-linux-amd64.tar.gz"
        sha256 "47187eb44e86c8a332fdd3503b8ec64fcff625622f5f0aef322329fe4161ba23"

        def install
          bin.install "easyp"
          output = Utils.popen_read("#{bin}/easyp completion bash")
          (bash_completion/"easyp").write output
          output = Utils.popen_read("#{bin}/easyp completion zsh")
          (zsh_completion/"_easyp").write output
          prefix.install_metafiles
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/easyp-tech/easyp/releases/download/v0.7.7/easyp-0.7.7-linux-armv6.tar.gz"
        sha256 "a225b04cce300421c344718bfc04ebdb0d2a0f88a1aa9d7f354ab55e15433fc6"

        def install
          bin.install "easyp"
          output = Utils.popen_read("#{bin}/easyp completion bash")
          (bash_completion/"easyp").write output
          output = Utils.popen_read("#{bin}/easyp completion zsh")
          (zsh_completion/"_easyp").write output
          prefix.install_metafiles
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/easyp-tech/easyp/releases/download/v0.7.7/easyp-0.7.7-linux-arm64.tar.gz"
        sha256 "70129d565011fbdea3be8fbc97b6175d1911bf8d702048c1b54145fbbd44dca1"

        def install
          bin.install "easyp"
          output = Utils.popen_read("#{bin}/easyp completion bash")
          (bash_completion/"easyp").write output
          output = Utils.popen_read("#{bin}/easyp completion zsh")
          (zsh_completion/"_easyp").write output
          prefix.install_metafiles
        end
      end
    end
  end

  test do
    system "#{bin}/easyp --version"
  end
end
